---

site_name: k8s@home | Docs
site_description: Docs for the k8s@home community
site_author: The k8s@home project
site_url: https://docs.k8s-at-home.com

repo_name: k8s-at-home/docs
repo_url: https://github.com/k8s-at-home/docs
edit_uri: "edit/main/docs/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  palette:
    primary: blue
    accent: indigo

docs_dir: ../docs

extra_css:
- ../docs/_static/custom.css

plugins:
- search

markdown_extensions:
- admonition
- meta
- codehilite:
    guess_lang: false
- toc:
    permalink: true
- pymdownx.superfences:
    highlight_code: true
- pymdownx.snippets
- pymdownx.tabbed
- pymdownx.tilde
- pymdownx.progressbar
- pymdownx.tasklist
- pymdownx.superfences
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
- Introduction: index.md
