---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint
        name: Run yamllint
        description: Lint yaml files
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.27.1
    hooks:
      - id: markdownlint
        name: Run markdownlint
        description: Lint markdown files
