---

name: Publish docs via GitHub Pages

concurrency: release-docs

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
    - 'docs-*'
    - main
    paths:
    - '.github/workflows/docs.yaml'
    - 'mkdocs.yaml'
    - 'docs/**'

env:
  MKDOCS_MATERIAL_INSIDER_TOKEN: ${{ secrets.MKDOCS_MATERIAL_INSIDER_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - name: Get k8s-at-home token
        id: get-app-token
        uses: getsentry/action-github-app-token@v1
        with:
          app_id: ${{ secrets.K8S_AT_HOME_APP_ID }}
          private_key: ${{ secrets.K8S_AT_HOME_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ steps.get-app-token.outputs.token }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Configure Git
        run: |
          git config user.name "k8s-at-home[bot]"
          git config user.email "<k8s-at-home[bot]@users.noreply.github.com>"

      - run: pip install git+https://${MKDOCS_MATERIAL_INSIDER_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: |
          pip install \
            mkdocs-minify-plugin>=0.3 \
            mkdocs-redirects>=1.0
      - run: mkdocs gh-deploy --config-file ./mkdocs.yaml --force
      - run: mkdocs --version
